### ISSUE TITLE
thank you for your article ,In mardy cifar-10 wideresnet model ，How did it achieve 44.35% accuracy?

### ISSUE THREAD

**Issue by liuye6666** [ermongroup/ODS#1]
Thank you for providing such a good article，In mardy cifar-10 wideresnet model ,Do you use any optimizer? Such as SGD, ADAM，I set the step size to 2 (2/255), the maximum disturbance is 8, the number of restarts is 20, the number of ODIs is 2 and the number of attacks is 20, but I can hardly get an accuracy of 44.35%, only 44.62%?I want to know if there are other detailed details, I am adapted from mardy's code。
 can you disclose the code of your test mardy cifar10 model? Thank you very much

**Comment by liuye6666** [comment]
I set the step size from 8 to1,total attack step is 20,for the number of attack step [0,3],[4,7],[8,14][15,19],the corresponding step size is 8,4,2,1,the number of ODI is 2,the max perturbation is 8，the ODI step size is 8， the restart time is 30,but get the 44.57?,I use the margin loss ,I did not use any optimizer，I tested it 3 times and I couldn’t reach 44.35%，only 44.5x%.

Thanks again for your article, and thank you very much for your reply

**Comment by y-tashi** [comment]
Hi, thank you for your interest in our paper!

Our experiment was also based on MadryLab's code. We used constant step size (=2) for PGD, which may make difference from your experiment. 
We added codes for ODI in tensorflow, so please check the code.

**Comment by liuye6666** [comment]
Thank you very much for your reply. It solved my problems . this is a good paper.
