### ISSUE TITLE
SimBA ODS is not based on SimBA?

### ISSUE THREAD

**Issue by machanic** [ermongroup/ODS#2]
I found that you name your algorithm based on SimBA, however you use the loss function, which is be used by SimBA. SimBA only uses the output probability to attack.

Am I right?

**Comment by y-tashi** [comment]
Hi, thank you for your interest.
First, we change adversarial loss for SimBA_ODS from the original paper, to avoid numerical issues(#1) and to follow the code of the Square Attack, which is a baseline in our paper.
We note that SimBA adopts the output probability as adversarial loss in their paper, so the difference from the original paper is a choice of adversarial loss and we refer to the attack in our code as SimBA. We confirmed that ODS also works well when we choose the output probability as adversarial loss.

(#1) probability is sometimes not updated from 1.0.
