### ISSUE TITLE
How to accelarate SimBA_ODS?

### ISSUE THREAD

**Issue by machanic** [ermongroup/ODS#3]
When I attack 1000 images using SimBA_ODS, I found that it runs too slow because each iteration requires a forward-backward of a surrogate model?
How to boost attack speed?

**Comment by y-tashi** [comment]
First, SimBA_ODS focuses not on wall-clock run time, but on query-efficiency.
While SimBA_ODS needs calculation to compute gradients for surrogate models, it reduces the number of queries to the targeted model. Please check "query" in output file.
To boost run time, one possible way is to calculate gradients with multiple images (i.e. batch). Our code runs per a single image and it is a part of the reason of long wall-clock run time.

**Comment by machanic** [comment]
I have run SimBA_ODS on L2 norm and L-inf norm attacks, However, I found that the SimBA-ODS fails to attack all 1000 images. Why. Maybe my modification of this attack is incorrect. I upload my revised script of your code here.
[SimBA_ODS.zip](https://github.com/ermongroup/ODS/files/5383352/SimBA_ODS.zip)
I will check your code again and verify the reason of the fail attack.

**Comment by y-tashi** [comment]
I briefly checked your code. cw_loss may have a problem. 
The direction is opposite, i.e. gt_logit - second_max_logit -> second_max_logit - gt_logit.
Please try to modify it and run again.

**Comment by machanic** [comment]
@y-tashi Thank you ! you are so kind, I re-run the code and it seems work properly.

**Comment by y-tashi** [comment]
You are welcome!
