### ISSUE TITLE
Do you miss one query count in SimBA ODS?

### ISSUE THREAD

**Issue by machanic** [ermongroup/ODS#4]
I notice that the query in this line https://github.com/ermongroup/ODS/blob/master/blackbox_simbaODS.py#L97
is not counted in `nQuery`.

https://github.com/ermongroup/ODS/blob/master/blackbox_simbaODS.py#L123 only counts for the query in line: https://github.com/ermongroup/ODS/blob/master/blackbox_simbaODS.py#L122

Why line 97 does not been counted in the `nQuery`?

**Comment by y-tashi** [comment]
You are correct. Thanks! 
We revised the code to add the query for the original image.
