### ISSUE TITLE
About the parameter: num_restarts

### ISSUE THREAD

**Issue by hcguoO0** [ermongroup/ODS#5]
In white-box attack, why do you run the code repeatedly with the parameter 'num_restarts'? I don't know whether the parameter 'num_restart' influences the result of your method, hoping for your answer.

**Comment by y-tashi** [comment]
Hi,
The purpose of restarts in white-box attack is to find new adversarial examples and improve attack performance by starting from random multiple starting points.
PGD attacks usually benefit from random restarts (i.e., not only for ODI-PGD). Random restarts is a common technique for evaluating defense models and other papers also use restarts. 
(e.g., https://arxiv.org/abs/1706.06083, https://openreview.net/pdf?id=HJlzxgBtwH)

**Comment by hcguoO0** [comment]
Thanks for your reply.
